#encoding=utf-8

CMSG_PING	= 1
SMSG_PONG	= 2
CMSG_LOGIN	= 3
SMSG_LOGIN	= 4
SMSG_LOGOUT	= 5
SMSG_RESULT	= 6
CMSG_MOVE	= 7
SMSG_MOVE	= 8
SMSG_ROOM_LIST	= 9
CMSG_ROOM_CREATE	= 10
CMSG_ROOM_ENTER	= 11
SMSG_ROOM_INFO	= 12
CMSG_ROOM_READY	= 13
CMSG_ROOM_LEAVE	= 14
SMSG_ROOM_LEAVE	= 15
SMSG_MAP_ENTER	= 16
CMSG_BOMB_BORN	= 17
SMSG_BOMB_BORN	= 18
SMSG_BOMB_EXPLODE	= 19
SMSG_ROLE_DEAD	= 20
SMSG_GAME_OVER	= 21

opcodes = {
	CMSG_PING	: "CMSG_PING",
	SMSG_PONG	: "SMSG_PONG",
	CMSG_LOGIN	: "CMSG_LOGIN",
	SMSG_LOGIN	: "SMSG_LOGIN",
	SMSG_LOGOUT	: "SMSG_LOGOUT",
	SMSG_RESULT	: "SMSG_RESULT",
	CMSG_MOVE	: "CMSG_MOVE",
	SMSG_MOVE	: "SMSG_MOVE",
	SMSG_ROOM_LIST	: "SMSG_ROOM_LIST",
	CMSG_ROOM_CREATE	: "CMSG_ROOM_CREATE",
	CMSG_ROOM_ENTER	: "CMSG_ROOM_ENTER",
	SMSG_ROOM_INFO	: "SMSG_ROOM_INFO",
	CMSG_ROOM_READY	: "CMSG_ROOM_READY",
	CMSG_ROOM_LEAVE	: "CMSG_ROOM_LEAVE",
	SMSG_ROOM_LEAVE	: "SMSG_ROOM_LEAVE",
	SMSG_MAP_ENTER	: "SMSG_MAP_ENTER",
	CMSG_BOMB_BORN	: "CMSG_BOMB_BORN",
	SMSG_BOMB_BORN	: "SMSG_BOMB_BORN",
	SMSG_BOMB_EXPLODE	: "SMSG_BOMB_EXPLODE",
	SMSG_ROLE_DEAD	: "SMSG_ROLE_DEAD",
	SMSG_GAME_OVER	: "SMSG_GAME_OVER"
	}
